image:
  repository: 076831690411.dkr.ecr.ap-northeast-2.amazonaws.com/neodohae_nestjs
  tag: b52e0d4fcce047a7e67e0f3dbf69b6f6787575bd
  port: 4200

service:
  name: neodohae-nestjs-service
  type: LoadBalancer
  port: 80
  targetPort: 4200

hpa:
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilization: 70
  targetMemoryUtilization: 70
