image:
  repository: 076831690411.dkr.ecr.ap-northeast-2.amazonaws.com/neodohae_nestjs
  tag: a0bbbdbf57eda3511bcc7ada44ec98cb12150641
  port: 4200
service:
  name: neodohae-nestjs-service
  type: LoadBalancer
  port: 80
  targetPort: 4200
hpa:
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilization: 70
  targetMemoryUtilization: 70
