image:
  repository: 076831690411.dkr.ecr.ap-northeast-2.amazonaws.com/neodohae_nestjs
  tag: 1cae6186c9c0da3bc253ba2baed7b8a4565ece28
  port: 4200
service:
  name: neodohae-nestjs-service
  type: LoadBalancer
  port: 80
  targetPort: 4200
hpa:
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilization: 70
  targetMemoryUtilization: 70
