image:
  repository: 076831690411.dkr.ecr.ap-northeast-2.amazonaws.com/neodohae_nestjs
  tag: cb7538054a9a34743c8d894b5562ff9e9c9c8787
  port: 4200
service:
  name: neodohae-nestjs-service
  type: LoadBalancer
  port: 80
  targetPort: 4200
hpa:
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilization: 70
  targetMemoryUtilization: 70
