image:
  repository: 076831690411.dkr.ecr.ap-northeast-2.amazonaws.com/neodohae_nestjs
  tag: 9d16880e6a027f2b84197ccf5f91468868b93e50
  port: 4200
service:
  name: neodohae-nestjs-service
  type: LoadBalancer
  port: 80
  targetPort: 4200
hpa:
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilization: 70
  targetMemoryUtilization: 70
