image:
  repository: 076831690411.dkr.ecr.ap-northeast-2.amazonaws.com/neodohae_spring_boot
  tag: ac3f07df7c246c7a4be42d83dd8a1b5422230e01
  port: 4300
service:
  name: neodohae-spring-boot-service
  type: LoadBalancer
  port: 80
  targetPort: 4300
hpa:
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilization: 70
  targetMemoryUtilization: 70
