image:
  repository: 076831690411.dkr.ecr.ap-northeast-2.amazonaws.com/neodohae_nextjs
  tag: b72fbb5fc070a812f7b1ea4df32a4b26dad5644f
  port: 4100
service:
  name: neodohae-nextjs-service
  type: LoadBalancer
  port: 80
  targetPort: 4100
hpa:
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilization: 70
  targetMemoryUtilization: 70
