image:
  repository: 076831690411.dkr.ecr.ap-northeast-2.amazonaws.com/neodohae_nextjs
  tag: 44af8d66b370b9624654db1f9e848cb63222cff1
  port: 4100

service:
  name: neodohae-nextjs-service
  type: LoadBalancer
  port: 80
  targetPort: 4100

hpa:
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilization: 70
  targetMemoryUtilization: 70
