image:
  repository: 076831690411.dkr.ecr.ap-northeast-2.amazonaws.com/neodohae_nextjs
  tag: daefe6e9caa3e657f84d6c0fc18152c1247e4127
  port: 4100
service:
  name: neodohae-nextjs-service
  type: LoadBalancer
  port: 80
  targetPort: 4100
hpa:
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilization: 70
  targetMemoryUtilization: 70
